# Generated by Django 3.1.4 on 2020-12-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mots_passe', models.CharField(max_length=256, verbose_name='Mot de passe')),
                ('refaire_motes_passe', models.CharField(max_length=256, verbose_name='Confirmation du mot de passe')),
                ('prenom', models.CharField(max_length=50, null=True, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('communaute', models.IntegerField(blank=True, null=True, verbose_name='Je crée un compte auprès de communauté')),
                ('nom_communaute', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de Communauté')),
                ('maison', models.IntegerField(blank=True, null=True, verbose_name='auprès de la maison de')),
                ('nom_maison', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de Maison')),
                ('parent', models.IntegerField(null=True)),
                ('responsable', models.IntegerField(blank=True, null=True)),
                ('role', models.IntegerField(blank=True, choices=[(0, 'Admin'), (5, 'Communauté'), (7, 'Responsable de Communauté'), (10, 'Maison'), (15, 'Responsable'), (18, 'Communautaire'), (20, 'Abonné')], default=20)),
                ('etat', models.IntegerField(blank=True, choices=[('Religieux(se)', 'Religieux(se)'), ('Diacre', 'Diacre'), ('Prêtre', 'Prêtre'), ('Individuel', 'Individuel'), ('Famille', 'Famille'), ('Parent seul', 'Parent seul')], null=True)),
                ('sex', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=10, null=True, verbose_name='Sexe')),
                ('etat_vie', models.CharField(choices=[('Religieux(se)', 'Religieux(se)'), ('Diacre', 'Diacre'), ('Prêtre', 'Prêtre'), ('Individuel', 'Individuel'), ('Famille', 'Famille'), ('Parent seul', 'Parent seul')], max_length=50, null=True, verbose_name='État de vie')),
                ('naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('code_postal', models.CharField(blank=True, max_length=50, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ville')),
                ('pays', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pays')),
                ('Tel', models.CharField(blank=True, max_length=50, null=True)),
                ('visuel', models.CharField(blank=True, max_length=255, null=True)),
                ('vip', models.IntegerField(blank=True, choices=[(1, 'Oui'), (0, 'Non')], default=0, null=True)),
                ('date_vip', models.DateField(blank=True, null=True, verbose_name='Date limite')),
                ('forfaits', models.IntegerField(choices=[(0, 'Non'), (1, '400'), (2, '800'), (3, '1200')], default=0, null=True, verbose_name='Forfait')),
                ('pourcentage', models.FloatField(blank=True, default=0, null=True, verbose_name='Pourcentage')),
                ('payeur', models.IntegerField(choices=[(0, 'Utilisateurs'), (1, 'Maison')], default=0, null=True, verbose_name='Payeur')),
                ('Ip', models.CharField(blank=True, max_length=50, null=True)),
                ('equipement', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('date_creer', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creer')),
                ('date_motifier', models.DateTimeField(auto_now=True, null=True, verbose_name='Date motifier')),
                ('has_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
