# Generated by Django 3.1.4 on 2020-12-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='communaute',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='date_vip',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='forfaits',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='maison',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='nom_communaute',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='nom_maison',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='payeur',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='pourcentage',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='vip',
        ),
        migrations.AlterField(
            model_name='compte',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='mots_passe',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='prenom',
            field=models.CharField(max_length=50, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='refaire_motes_passe',
            field=models.CharField(max_length=256, verbose_name='确认密码'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, '管理员'), (5, '负责人'), (10, '老师'), (15, '会员'), (20, '订阅者')], default=20),
        ),
        migrations.AlterField(
            model_name='compte',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='Homme', max_length=10, null=True, verbose_name='Sexe'),
        ),
    ]
