# Generated by Django 3.1.4 on 2020-12-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20201211_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='code_postal',
        ),
        migrations.AlterField(
            model_name='compte',
            name='Tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='etat_vie',
            field=models.CharField(choices=[('Religieux(se)', 'Religieux(se)'), ('Diacre', 'Diacre'), ('Prêtre', 'Prêtre'), ('Individuel', 'Individuel'), ('Famille', 'Famille'), ('Parent seul', 'Parent seul')], max_length=50, null=True, verbose_name='个人情况'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='pays',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, '全局管理员'), (5, '管理员'), (10, '负责人'), (15, '老师'), (20, '订阅者')], default=20),
        ),
        migrations.AlterField(
            model_name='compte',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='Homme', max_length=10, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='ville',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='城市'),
        ),
    ]
