# Generated by Django 3.1.4 on 2020-12-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20201212_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='cathegorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('parent', models.IntegerField(default=0, verbose_name='父分类')),
                ('note', models.TextField(null=True, verbose_name='标记')),
                ('user_id', models.IntegerField(null=True)),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('date_creer', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creer')),
                ('date_motifier', models.DateTimeField(auto_now=True, null=True, verbose_name='Date motifier')),
            ],
        ),
        migrations.AlterField(
            model_name='compte',
            name='naissance',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='sex',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=10, null=True, verbose_name='性别'),
        ),
    ]
