# Generated by Django 3.1.4 on 2020-12-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20201212_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='cathegorie',
            name='original',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cathegorie',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='标记'),
        ),
        migrations.AlterField(
            model_name='cathegorie',
            name='parent',
            field=models.IntegerField(blank=True, default=1, verbose_name='父分类'),
        ),
    ]
