# Generated by Django 3.1.4 on 2020-12-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20201212_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Titre')),
                ('contenu', models.TextField(null=True, verbose_name='Contenu')),
                ('observation', models.IntegerField(choices=[(1, '是'), (0, '否')], default=1, verbose_name='Publier')),
                ('fichier_audio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Audio')),
                ('fichier_video', models.CharField(blank=True, max_length=255, null=True, verbose_name='Video')),
                ('user_id', models.IntegerField(null=True)),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('date_creer', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creer')),
                ('date_motifier', models.DateTimeField(auto_now=True, null=True, verbose_name='Date motifier')),
            ],
        ),
    ]
