# Generated by Django 3.1.4 on 2020-12-13 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_article_cathegorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cathegorie',
        ),
        migrations.AddField(
            model_name='article',
            name='cathegorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.cathegorie', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=models.TextField(null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fichier_audio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='音频'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fichier_video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='article',
            name='observation',
            field=models.IntegerField(choices=[(1, '是'), (0, '否')], default=1, verbose_name='发布'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='标题'),
        ),
    ]
