# Generated by Django 3.1.4 on 2020-12-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20201213_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cathegorie',
        ),
        migrations.AddField(
            model_name='article',
            name='cathegorie',
            field=models.ManyToManyField(to='index.cathegorie', verbose_name='分类'),
        ),
    ]
