# Generated by Django 3.1.4 on 2020-12-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20201213_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='cathegorie',
            name='ordre',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
