# Generated by Django 3.1.4 on 2020-12-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_cathegorie_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visuel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Visuel'),
        ),
    ]
