# Generated by Django 3.1.4 on 2020-12-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_article_visuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='dossiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_org', models.CharField(max_length=255, null=True, verbose_name='Nom')),
                ('nom', models.CharField(max_length=255, null=True, verbose_name='Nom')),
                ('type', models.CharField(max_length=255, null=True, verbose_name='Nom')),
                ('duration', models.FloatField(null=True)),
                ('lien', models.CharField(max_length=255, null=True, verbose_name='Nom')),
                ('stantard', models.CharField(max_length=255, null=True, verbose_name='Nom')),
                ('thumb', models.CharField(max_length=255, null=True, verbose_name='Nom')),
                ('file', models.FileField(upload_to='media/%Y/%m/%d/')),
                ('date_creer', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creer')),
                ('date_motifier', models.DateTimeField(auto_now=True, null=True, verbose_name='Date motifier')),
                ('user_id', models.IntegerField(null=True, verbose_name='Nom')),
                ('maison', models.IntegerField(null=True, verbose_name='Nom')),
            ],
        ),
    ]
