# Generated by Django 3.1.4 on 2020-12-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_dossiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lire',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
