# Generated by Django 3.1.4 on 2021-01-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_article_lire'),
    ]

    operations = [
        migrations.AddField(
            model_name='cathegorie',
            name='observation',
            field=models.IntegerField(choices=[(1, '是'), (0, '否')], default=1, verbose_name='显示'),
        ),
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=models.TextField(blank=True, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='lire',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
