# Generated by Django 3.1.4 on 2021-02-23 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20210115_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cathegorie',
        ),
    ]
