# Generated by Django 3.1.4 on 2021-02-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_remove_article_cathegorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cathegorie',
            field=models.ManyToManyField(to='index.cathegorie', verbose_name='分类'),
        ),
    ]
