# Generated by Django 3.1.4 on 2021-03-25 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_article_cathegorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='pray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('payer', models.IntegerField(blank=True, default=0, null=True)),
                ('louer', models.IntegerField(blank=True, default=0, null=True)),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('date_creer', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creer')),
                ('date_motifier', models.DateTimeField(auto_now=True, null=True, verbose_name='Date motifier')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.compte')),
            ],
        ),
    ]
