# Generated by Django 3.1.4 on 2021-03-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_pray'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='saintnom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='圣名'),
        ),
    ]
