# Generated by Django 3.1.4 on 2021-03-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_compte_saintnom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pray',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
