# Generated by Django 3.1.4 on 2021-03-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_auto_20210325_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='标题')),
                ('contenu', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('observation', models.IntegerField(choices=[(1, '是'), (0, '否')], default=1, verbose_name='发布')),
                ('ordre', models.IntegerField(blank=True, default=0, null=True)),
                ('parent', models.IntegerField(blank=True, default=0, null=True)),
                ('visuel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Visuel')),
                ('fichier_audio', models.CharField(blank=True, max_length=255, null=True, verbose_name='音频')),
                ('fichier_video', models.CharField(blank=True, max_length=255, null=True, verbose_name='视频')),
                ('lire', models.IntegerField(blank=True, default=0, null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('date_creer', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creer')),
                ('date_motifier', models.DateTimeField(auto_now=True, null=True, verbose_name='Date motifier')),
            ],
        ),
    ]
