# Generated by Django 3.1.4 on 2021-03-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='live',
            name='fichier_audio',
        ),
        migrations.RemoveField(
            model_name='live',
            name='fichier_video',
        ),
        migrations.AddField(
            model_name='live',
            name='live_video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='直播地址'),
        ),
        migrations.AddField(
            model_name='live',
            name='relive_video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='回播地址'),
        ),
    ]
