# Generated by Django 3.1.4 on 2021-03-25 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_auto_20210325_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='professeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.compte'),
        ),
    ]
