# Generated by Django 3.1.4 on 2021-03-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_live_professeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='livepushurl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='livepushurl'),
        ),
        migrations.AddField(
            model_name='live',
            name='logininfokey',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='logininfokey'),
        ),
    ]
