# Generated by Django 3.1.4 on 2021-04-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='favorise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, null=True, verbose_name='标题')),
                ('post_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('date_creer', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creer')),
            ],
        ),
    ]
