# Generated by Django 3.1.4 on 2021-04-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0027_favorise'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(max_length=255, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
