# Generated by Django 3.1.4 on 2021-04-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_auto_20210429_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_id',
        ),
    ]
