# Generated by Django 3.1.4 on 2021-05-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0029_remove_feedback_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='简单描述'),
        ),
    ]
