# Generated by Django 3.1.4 on 2021-05-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='简单描述'),
        ),
        migrations.AddField(
            model_name='live',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='简单描述'),
        ),
    ]
