# Generated by Django 3.1.4 on 2021-05-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0032_article_date_publier'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='color',
            field=models.CharField(max_length=50, null=True, verbose_name='颜色'),
        ),
    ]
