# Generated by Django 3.1.4 on 2021-05-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0033_article_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='标题颜色'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_motifier',
            field=models.DateTimeField(null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_publier',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='发布时间'),
        ),
    ]
