# Generated by Django 3.1.4 on 2021-07-02 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0034_auto_20210523_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_motifier',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.CreateModel(
            name='article_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('observation', models.IntegerField(choices=[(1, '是'), (0, '否')], default=1, verbose_name='发布')),
                ('date_creer', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creer')),
                ('parent', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.article')),
                ('user_id', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.compte')),
            ],
        ),
    ]
