# Generated by Django 3.1.4 on 2021-10-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0035_auto_20210702_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='email',
            field=models.CharField(max_length=256, unique=True, verbose_name='邮箱/手机号'),
        ),
    ]
