# Generated by Django 3.1.4 on 2021-10-05 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0036_auto_20211005_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='article', max_length=255, null=True, verbose_name='标题')),
                ('contenu', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('observation', models.IntegerField(choices=[(1, '是'), (0, '否')], default=1, verbose_name='发布')),
                ('date_creer', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creer')),
                ('parent', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.article')),
                ('user_id', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.compte')),
            ],
        ),
    ]
