# Generated by Django 3.1.4 on 2021-10-06 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0038_auto_20211006_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_cours',
            name='parent',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.cours'),
        ),
    ]
