# Generated by Django 3.1.4 on 2021-10-08 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0039_auto_20211006_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_comments',
            name='parent_comment',
            field=models.IntegerField(default=0, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='article_comments',
            name='type',
            field=models.CharField(default='article', max_length=255, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='article_comments',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.compte'),
        ),
    ]
