# Generated by Django 3.1.4 on 2021-10-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0040_auto_20211008_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_comments',
            name='parent_comment',
            field=models.IntegerField(default=0, verbose_name='回复'),
        ),
    ]
