# Generated by Django 3.1.4 on 2021-10-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0041_auto_20211008_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_cours',
            name='parent_comment',
            field=models.IntegerField(default=0, verbose_name='回复'),
        ),
    ]
