# Generated by Django 3.1.4 on 2021-10-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0042_comments_cours_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_comments',
            name='ordre',
            field=models.IntegerField(blank=True, default=0, verbose_name='显示顺序'),
        ),
        migrations.AddField(
            model_name='comments_cours',
            name='ordre',
            field=models.IntegerField(blank=True, default=0, verbose_name='显示顺序'),
        ),
    ]
