# Generated by Django 3.1.4 on 2021-10-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0043_auto_20211010_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='verifi_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0, null=True, verbose_name='类型')),
                ('tel', models.CharField(max_length=255, null=True, verbose_name='手机号')),
                ('cod', models.CharField(max_length=255, null=True, verbose_name='验证码')),
                ('date_creer', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creer')),
            ],
        ),
    ]
