# Generated by Django 3.1.4 on 2021-10-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0044_verifi_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifi_code',
            old_name='cod',
            new_name='code',
        ),
    ]
