# Generated by Django 3.1.4 on 2021-10-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0045_auto_20211011_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifi_code',
            name='date_creer',
            field=models.DateTimeField(null=True, verbose_name='Date creer'),
        ),
    ]
