# Generated by Django 3.1.4 on 2021-10-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0046_auto_20211011_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifi_code',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='Date creer'),
        ),
    ]
