# Generated by Django 3.1.4 on 2021-10-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0047_verifi_code_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifi_code',
            name='time',
        ),
        migrations.AlterField(
            model_name='verifi_code',
            name='date_creer',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creer'),
        ),
    ]
