# Generated by Django 3.1.4 on 2021-10-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0048_auto_20211011_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='音频时长'),
        ),
    ]
