# Generated by Django 3.1.4 on 2021-10-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0049_article_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='音频时长'),
        ),
    ]
