# Generated by Django 3.1.4 on 2021-10-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0050_cours_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='ordre',
            field=models.IntegerField(blank=True, default=0, verbose_name='显示顺序'),
        ),
        migrations.AddField(
            model_name='comments',
            name='parent_comment',
            field=models.IntegerField(default=0, verbose_name='回复'),
        ),
        migrations.AddField(
            model_name='comments',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='parent',
            field=models.IntegerField(default=0, null=True, verbose_name='article'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='type',
            field=models.CharField(default='article', max_length=255, null=True, verbose_name='类型'),
        ),
    ]
