# Generated by Django 3.1.4 on 2021-10-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0051_auto_20211013_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments_cours',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comments_cours',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='comments',
            name='parent',
            field=models.IntegerField(default=0, null=True, verbose_name='文章id'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='parent_comment',
            field=models.IntegerField(blank=True, default=0, verbose_name='回复'),
        ),
        migrations.DeleteModel(
            name='article_comments',
        ),
        migrations.DeleteModel(
            name='comments_cours',
        ),
    ]
