# Generated by Django 3.1.4 on 2021-10-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0052_auto_20211013_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
