# Generated by Django 3.1.4 on 2021-10-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0053_feedback_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='parent',
            field=models.IntegerField(default=0, null=True, verbose_name='文章id'),
        ),
    ]
