# Generated by Django 3.1.4 on 2021-10-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0054_feedback_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, null=True, verbose_name='Titre')),
                ('contenu', models.TextField(null=True, verbose_name='Setting')),
                ('user_id', models.IntegerField(null=True)),
                ('date_creer', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creer')),
                ('date_motifier', models.DateTimeField(auto_now=True, null=True, verbose_name='Date motifier')),
            ],
        ),
    ]
