# Generated by Django 3.1.4 on 2021-10-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0055_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='note',
            field=models.TextField(null=True, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='contenu',
            field=models.TextField(null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(max_length=255, null=True, verbose_name='关键字'),
        ),
    ]
