# Generated by Django 3.1.4 on 2022-08-29 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0056_auto_20211028_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='new_contenu',
            field=models.TextField(blank=True, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_publier',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.compte'),
        ),
        migrations.AlterField(
            model_name='live',
            name='professeur',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.compte'),
        ),
    ]
