# Generated by Django 5.0.4 on 2024-04-27 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0057_auto_20220829_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='new_contenu',
            field=models.TextField(blank=True, null=True, verbose_name='新内容'),
        ),
        migrations.CreateModel(
            name='cathegorie_cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('note', models.TextField(blank=True, null=True, verbose_name='标记')),
                ('original', models.IntegerField(blank=True, null=True)),
                ('ordre', models.IntegerField(blank=True, default=0, null=True)),
                ('observation', models.IntegerField(choices=[(1, '是'), (0, '否')], default=1, verbose_name='显示')),
                ('user_id', models.IntegerField(null=True)),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('date_creer', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creer')),
                ('date_motifier', models.DateTimeField(auto_now=True, null=True, verbose_name='Date motifier')),
                ('parent', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.cathegorie_cours')),
            ],
        ),
    ]
