# Generated by Django 5.0.4 on 2024-04-27 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0058_alter_article_new_contenu_cathegorie_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='cathegorie',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.cathegorie_cours', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='cathegorie_cours',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.cathegorie_cours'),
        ),
    ]
