# Generated by Django 5.0.4 on 2024-04-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0059_cours_cathegorie_alter_cathegorie_cours_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cathegorie',
            name='visuel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Visuel'),
        ),
        migrations.AddField(
            model_name='cathegorie_cours',
            name='visuel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Visuel'),
        ),
    ]
