# Generated by Django 5.0.4 on 2024-04-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0060_cathegorie_visuel_cathegorie_cours_visuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='visuel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='cathegorie',
            name='visuel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='cathegorie_cours',
            name='visuel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='封面'),
        ),
    ]
