# Generated by Django 5.0.4 on 2024-04-27 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0061_alter_article_visuel_alter_cathegorie_visuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathegorie',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.cathegorie'),
        ),
    ]
