# Generated by Django 5.0.4 on 2024-06-14 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0062_alter_cathegorie_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='sg_bibleBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='卷名')),
                ('brev', models.CharField(max_length=255, null=True, verbose_name='简写')),
                ('mark', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='公共标记')),
            ],
        ),
        migrations.AlterField(
            model_name='cathegorie',
            name='parent',
            field=models.IntegerField(blank=True, default=1, verbose_name='父分类'),
        ),
        migrations.CreateModel(
            name='sg_bible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='日期')),
                ('contenu', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('livre', models.CharField(max_length=20, null=True, verbose_name='标记')),
                ('chapitre', models.IntegerField(null=True, verbose_name='章')),
                ('partie', models.IntegerField(null=True, verbose_name='节')),
                ('paragraph', models.IntegerField(null=True, verbose_name='分段')),
                ('commun', models.CharField(blank=True, max_length=100, null=True, verbose_name='公共参数')),
                ('book', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.sg_biblebook')),
            ],
        ),
    ]
