# Generated by Django 5.0.4 on 2024-06-14 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0063_sg_biblebook_alter_cathegorie_parent_sg_bible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sg_bible',
            name='book',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.sg_biblebook'),
        ),
    ]
