# Generated by Django 5.0.4 on 2024-06-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0064_alter_sg_bible_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sg_bible',
        ),
    ]
