# Generated by Django 5.0.4 on 2024-06-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0065_delete_sg_bible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathegorie',
            name='parent',
            field=models.IntegerField(blank=True, default=0, verbose_name='父分类'),
        ),
    ]
