# Generated by Django 5.0.4 on 2024-06-14 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0066_alter_cathegorie_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sg_bibleBook',
        ),
    ]
