# Generated by Django 5.0.4 on 2024-06-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0067_delete_sg_biblebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='sg_bibleBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='卷名')),
                ('brev', models.CharField(max_length=255, null=True, verbose_name='简写')),
                ('mark', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='公共标记')),
            ],
        ),
    ]
