# Generated by Django 5.0.4 on 2024-06-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0069_sg_bible'),
    ]

    operations = [
        migrations.CreateModel(
            name='sg_lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impair', models.IntegerField(blank=True, null=True, verbose_name='单双年')),
                ('abc', models.IntegerField(blank=True, null=True, verbose_name='甲乙丙')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('fete', models.IntegerField(blank=True, null=True, verbose_name='单双年')),
                ('sign', models.CharField(blank=True, max_length=255, null=True, verbose_name='标记')),
                ('lecture1', models.CharField(blank=True, max_length=255, null=True, verbose_name='读经一')),
                ('psaume', models.CharField(blank=True, max_length=255, null=True, verbose_name='圣咏')),
                ('lecture2', models.CharField(blank=True, max_length=255, null=True, verbose_name='读经二')),
                ('evangile', models.CharField(blank=True, max_length=255, null=True, verbose_name='福音')),
            ],
        ),
    ]
