# Generated by Django 5.0.4 on 2024-06-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0070_sg_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sg_lecture',
            name='evangile',
        ),
        migrations.RemoveField(
            model_name='sg_lecture',
            name='lecture1',
        ),
        migrations.RemoveField(
            model_name='sg_lecture',
            name='lecture2',
        ),
        migrations.RemoveField(
            model_name='sg_lecture',
            name='psaume',
        ),
        migrations.AddField(
            model_name='sg_lecture',
            name='complies',
            field=models.TextField(blank=True, null=True, verbose_name='夜祷'),
        ),
        migrations.AddField(
            model_name='sg_lecture',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='介绍'),
        ),
        migrations.AddField(
            model_name='sg_lecture',
            name='laudes',
            field=models.TextField(blank=True, null=True, verbose_name='早祷'),
        ),
        migrations.AddField(
            model_name='sg_lecture',
            name='lecture',
            field=models.TextField(blank=True, null=True, verbose_name='诵读'),
        ),
        migrations.AddField(
            model_name='sg_lecture',
            name='messe',
            field=models.TextField(blank=True, null=True, verbose_name='弥撒'),
        ),
        migrations.AddField(
            model_name='sg_lecture',
            name='none',
            field=models.TextField(blank=True, null=True, verbose_name='午后'),
        ),
        migrations.AddField(
            model_name='sg_lecture',
            name='sexte',
            field=models.TextField(blank=True, null=True, verbose_name='午时'),
        ),
        migrations.AddField(
            model_name='sg_lecture',
            name='tierce',
            field=models.TextField(blank=True, null=True, verbose_name='午前'),
        ),
        migrations.AddField(
            model_name='sg_lecture',
            name='vepre1',
            field=models.TextField(blank=True, null=True, verbose_name='晚祷'),
        ),
    ]
