# Generated by Django 5.0.4 on 2024-06-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0071_remove_sg_lecture_evangile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sg_biblebook',
            name='chapitre',
            field=models.TextField(blank=True, null=True, verbose_name='章节'),
        ),
        migrations.AlterField(
            model_name='sg_lecture',
            name='fete',
            field=models.IntegerField(blank=True, null=True, verbose_name='节庆日'),
        ),
    ]
