# Generated by Django 5.0.4 on 2024-06-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0072_sg_biblebook_chapitre_alter_sg_lecture_fete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sg_lecture',
            old_name='vepre1',
            new_name='vepre',
        ),
        migrations.AlterField(
            model_name='sg_lecture',
            name='abc',
            field=models.IntegerField(blank=True, choices=[('0', 'A'), ('1', 'B'), ('2', 'C')], null=True, verbose_name='甲乙丙'),
        ),
        migrations.AlterField(
            model_name='sg_lecture',
            name='fete',
            field=models.IntegerField(blank=True, choices=[('0', '纪'), ('1', '节日'), ('2', '庆日')], null=True, verbose_name='节庆日'),
        ),
        migrations.AlterField(
            model_name='sg_lecture',
            name='impair',
            field=models.IntegerField(blank=True, choices=[('1', '单数年'), ('0', '双数年')], null=True, verbose_name='单双年'),
        ),
    ]
