# Generated by Django 5.0.4 on 2024-10-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0076_alter_sg_lecture_abc_alter_sg_lecture_fete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='cathegorie',
        ),
        migrations.AddField(
            model_name='cours',
            name='cathegorie',
            field=models.ManyToManyField(to='index.cathegorie_cours', verbose_name='分类'),
        ),
    ]
