# Generated by Django 5.0.4 on 2024-10-21 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0077_remove_cours_cathegorie_cours_cathegorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='cathegorie',
        ),
        migrations.AddField(
            model_name='cours',
            name='cathegorie',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.cathegorie_cours', verbose_name='分类'),
        ),
    ]
