# Generated by Django 5.0.4 on 2025-10-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0078_remove_cours_cathegorie_cours_cathegorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='frequency_date',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='重复时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='new_contenu',
            field=models.TextField(blank=True, default='[]', null=True, verbose_name='新内容'),
        ),
    ]
