# Generated by Django 5.0.4 on 2026-03-07 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0079_article_frequency_date_alter_article_new_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, '全局管理员'), (5, '管理员'), (10, '负责人'), (15, '老师'), (20, '订阅者'), (25, '被屏蔽')], default=20),
        ),
        migrations.CreateModel(
            name='app_index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('type', models.CharField(blank=True, choices=[('single', '单显示'), ('loops', '循环')], max_length=255, null=True, verbose_name='类型')),
                ('days', models.IntegerField(default=1, null=True, verbose_name='显示几天')),
                ('date_creer', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date creer')),
                ('cathegory', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.cathegorie')),
                ('parent', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.app_index')),
                ('user_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.compte')),
            ],
        ),
    ]
